web:
    build: ./
    hostname: webhost
    restart: always
    volumes:
        - /usr/src/app/public/files
    links:
        - "mongodb"
    depends_on:
        - mongodb
    ports:
        - "3000:3000"
#################
mongodb:
    image: mongo:latest
    hostname: dbhost
    restart: always
    volumes_from:
        - storage-mongo  
    ports:
        - "27017:27017"
    environment:
        - MONGO_USERNAME=chat
        - MONGO_PASSWORD=chat
        - MONGO_PORT_27017_TCP_ADDR=dbhost
        - MONGO_PORT_27017_TCP_PORT=27017
        - MONGO_INSTANCE_NAME=chat

#################
storage-mongo:
    build: ./docker/storage/mongo
    volumes:
        - /data/db 
        - /data/configdb