web:
    image: ./docker/app
    hostname: webhost
    restart: always
    volumes:
        - /usr/src/app/public/files
    links:
        - "db"
    # ports:
    #     - "80:80"
#################
db:
    image: mongo:latest
    hostname: dbhost
    restart: always
    volumes_from:
        - storage-mongo
    environment:
        - MONGO_USERNAME=chat
        - MONGO_PASSWORD=chat
        - MONGO_PORT_27017_TCP_ADDR=dbhost
        - MONGO_PORT_27017_TCP_PORT=27017
        - MONGO_INSTANCE_NAME=chat

#################
storage-mongo:
    build: ./docker/storage/mongo
    volumes:
        - /data/db 
        - /data/configdb